var herbData = [
  {
    "Herb":"Calea zacatechichi",
    "Category":"Oneirogen",
    "Effects":"Vivid\/lucid dreams, dream recall",
    "Preparation":"Bitter tea or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83e\udde0 Dream, \u2705 Safe",
    "Mechanism of Action":"Effects attributed to flavones and germacrolides modulating cholinergic and possibly serotonergic pathways, enhancing dream-related neurochemistry [0, 1, 0, 11].",
    "Pharmacokinetics":"Consumed as bitter tea or smoked: onset 20\u201345\u202fmin; duration ~2\u20133\u202fh; likely metabolized hepatically [0, 1, 0, 21].",
    "Therapeutic Uses":"Traditional Mexican use for dream enhancement, divination, and improvement of dream recall [0, 6].",
    "Side Effects":"Bitter taste, nausea, vomiting; mild sedation [0, 6].",
    "Contraindications":"Avoid during pregnancy and combine cautiously with sedatives [0, 16].",
    "Drug Interactions":"Potentiates CNS depressants [0, 21].",
    "Toxicity":"Low reported toxicity; high doses may cause dizziness or vomiting [0, 16].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Silene capensis",
    "Category":"Oneirogen",
    "Effects":"Deep dreaming, ancestor contact",
    "Preparation":"Cold water root brew",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa",
    "Tags":"\u2615 Brewable, \ud83e\udde0 Dream, \u2705 Safe",
    "Mechanism of Action":"Contains triterpene saponins, alkaloids, and diterpenoids that may modulate cholinergic and GABAergic activity, enhancing REM sleep and dream vividness [0, 2, 0, 22].",
    "Pharmacokinetics":"Traditionally consumed as cold water infusion: onset ~30\u201360\u202fmin; effects last several hours [0, 7].",
    "Therapeutic Uses":"Promotes vivid and lucid dreaming; used in traditional Xhosa dream rituals [0, 2, 0, 7].",
    "Side Effects":"Rare; mild gastrointestinal upset and drowsiness in high amounts [0, 2].",
    "Contraindications":"Pregnancy and use with CNS depressants [0, 12].",
    "Drug Interactions":"May potentiate sedative effects of other herbs or medications [0, 22].",
    "Toxicity":"Low; no significant toxicity reported in traditional use [0, 2].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Entada rheedii",
    "Category":"Oneirogen",
    "Effects":"Dream enhancement, trance",
    "Preparation":"Seed powder or chew",
    "Intensity":"Moderate",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83d\udc8a Oral, \ud83e\udde0 Dream, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Traditionally consumed as cold water infusion; onset ~1\u20132\u202fh; effects last ~6\u20138\u202fh [0, 11].",
    "Therapeutic Uses":"Dream enhancement, lucid dreaming, traditional remedy for diarrhea and stomach aches [0, 6, 0, 11].",
    "Side Effects":"Mild GI upset, drowsiness; rare nausea [0, 6].",
    "Contraindications":"Pregnancy, lactation, hypersensitivity [0, 6].",
    "Drug Interactions":"May potentiate CNS depressants; caution with anticholinergics [0, 6].",
    "Toxicity":"Low; no severe toxicity reported in traditional use [0, 6].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Mugwort",
    "Category":"Oneirogen",
    "Effects":"Lucid dreams, astral travel",
    "Preparation":"Tea, smoke, or pillow herb",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83e\udde0 Dream, \u2705 Safe",
    "Mechanism of Action":"Contains thujone, a GABAA antagonist; may also modulate cholinergic systems [9, 9].",
    "Pharmacokinetics":"Smoked or tea; onset 20\u201340\u202fmin; duration ~1\u20132\u202fh [9, 9].",
    "Therapeutic Uses":"Lucid dreaming, digestive support, menstrual aid [9, 9].",
    "Side Effects":"Headache, nausea, dizziness; risk in pregnancy and seizure disorders [9, 9].",
    "Contraindications":"Pregnancy, allergies to ragweed, epilepsy [9, 9].",
    "Drug Interactions":"Avoid with CNS depressants and anticonvulsants [9, 9].",
    "Toxicity":"Contains thujone and other essential oils that are toxic in high doses.",
    "Toxicity \/ LD50":"Thujone LD50 ~87\u2013120 mg\/kg in mice; caution advised at high doses or chronic use."
  },
  {
    "Herb":"Heimia salicifolia (Sinicuichi)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Auditory hallucinations, slowed time",
    "Preparation":"Fermented sun tea",
    "Intensity":"Moderate",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83e\uddea Fermented, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":"Alkaloids may affect auditory processing and blood flow, potentially modulating neurotransmission [9, 4].",
    "Pharmacokinetics":"Traditionally fermented sun tea; slow onset 15\u201345\u202fmin; duration ~2\u20133\u202fh [9, 4].",
    "Therapeutic Uses":"Divination, auditory changes, euphoria in folk practices [9, 4].",
    "Side Effects":"Dry mouth, muscle relaxation, altered hearing [9, 4].",
    "Contraindications":"Avoid with alcohol or CNS depressants, pregnancy [9, 4].",
    "Drug Interactions":"None known; caution with psychiatric medications [9, 4].",
    "Toxicity":"Low toxicity; high doses may cause mild sedation or nausea [9, 4].",
    "Toxicity \/ LD50":"Not well established; no fatal doses reported in traditional use."
  },
  {
    "Herb":"Sceletium tortuosum (Kanna)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mood lift, empathy, sociability",
    "Preparation":"Chew, snuff, extract",
    "Intensity":"Moderate",
    "Onset":"30-60 min",
    "Legal Status":"Legal, sometimes restricted",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83d\udc8a Oral, \ud83d\udcab Euphoria, \u26a0\ufe0f Restricted",
    "Mechanism of Action":"Selective serotonin reuptake inhibition (SSRI) and phosphodiesterase-4 (PDE4) inhibition [9, 4].",
    "Pharmacokinetics":"Oral onset 20\u201360\u202fmin; duration 2\u20134\u202fh [9, 4].",
    "Therapeutic Uses":"Mood enhancement, anti-anxiety, social facilitation [9, 4].",
    "Side Effects":"Headache, nausea, mild sedation [9, 4].",
    "Contraindications":"Do not combine with other serotonergic substances; pregnancy [9, 4].",
    "Drug Interactions":"SSRIs, MAOIs, stimulants [9, 4].",
    "Toxicity":"Low toxicity at traditional doses [9, 4].",
    "Toxicity \/ LD50":"Not established in humans; high safety margin observed in animal studies."
  },
  {
    "Herb":"Blue Lotus (Nymphaea caerulea)",
    "Category":"Other",
    "Effects":"Euphoria, aphrodisiac, dreamy calm",
    "Preparation":"Wine soak, smoke, tea",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Contains aporphine and nuciferine; dopamine receptor modulation and mild sedative effect.",
    "Pharmacokinetics":"Smoked or soaked in wine; onset rapid (5\u201320 min); duration ~1\u20133 hrs.",
    "Therapeutic Uses":"Mild euphoria, anxiety relief, and aphrodisiac in traditional use.",
    "Side Effects":"Drowsiness, mild dizziness at high doses.",
    "Contraindications":"Pregnancy, avoid with dopaminergic drugs.",
    "Drug Interactions":"Potential additive effects with CNS depressants.",
    "Toxicity":"Low toxicity; no serious effects reported from traditional use.",
    "Toxicity \/ LD50":"Not established; no reported lethal doses."
  },
  {
    "Herb":"Wild Dagga",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Cannabis-like buzz, mild euphoria",
    "Preparation":"Smoke or extract",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \ud83d\udcab Euphoria, \u2705 Safe",
    "Mechanism of Action":"Contains labdane diterpenes such as leonurine and marrubiin; marrubiin modulates prostaglandin synthesis and exhibits anti-inflammatory and analgesic effects, while leonurine exhibits cardioprotective and neuroprotective properties [0, 4, 0, 0].",
    "Pharmacokinetics":"Leaf extracts via oral ingestion or smoking: rapid onset (5\u201310\u202fmin); marrubiin peak plasma ~1\u20132\u202fh; metabolites excreted renally [0, 1].",
    "Therapeutic Uses":"Traditional analgesic, anti-inflammatory, antidiabetic, anxiolytic, pulmonary tonic; used for coughs, fevers, diabetes, hypertension [0, 7].",
    "Side Effects":"Dizziness, hypotension, gastrointestinal upset at high doses; potential hepatotoxicity with chronic use [0, 5, 0, 8].",
    "Contraindications":"Pregnancy, hypotension, use with diabetic or antihypertensive medications [0, 5].",
    "Drug Interactions":"Additive hypotensive and antidiabetic effects; caution when combined with antihypertensives and antidiabetic agents [0, 5].",
    "Toxicity":"Animal acute toxicity at 3200\u202fmg\/kg caused mortality; high doses alter hematological parameters [0, 5].",
    "Toxicity \/ LD50":"Animal acute toxicity at 3200\u202fmg\/kg caused mortality; high doses alter hematological parameters [0, 5]."
  },
  {
    "Herb":"Damiana",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Aphrodisiac, relaxing, mood lifting",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal, banned in some countries",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udcab Euphoria, \u2705 Safe",
    "Mechanism of Action":"Mild MAOI activity and possible CB1 receptor modulation.",
    "Pharmacokinetics":"Oral ingestion as tea or extract: onset ~30\u201360\u202fmin; detailed kinetic data limited.",
    "Therapeutic Uses":"Aphrodisiac, mood enhancer, anxiolytic, gastrointestinal tonic; used in liqueurs and smoking blends for mild psychoactive effects [1, 10, 1, 7].",
    "Side Effects":"None significant reported; excessive doses may cause insomnia or headache [1, 5].",
    "Contraindications":"Pregnancy and lactation due to insufficient safety data; avoid in individuals sensitive to caffeine [1, 5].",
    "Drug Interactions":"Potential additive effects with sedatives and stimulants; caution with hypoglycemic and hypotensive medications [1, 7].",
    "Toxicity":"Low; no lethal toxicity reported at traditional doses [1, 5].",
    "Toxicity \/ LD50":"No established LD50; considered non-toxic in traditional use."
  },
  {
    "Herb":"Nelumbo nucifera (Sacred Lotus)",
    "Category":"Other",
    "Effects":"Spiritual clarity, calming euphoria",
    "Preparation":"Tea, tincture, smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83e\udde0 Cognitive, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Oral leaf extracts: peak plasma levels of nucleiferine and n-nornuciferine ~1\u20132\u202fh; compounds cross blood\u2013brain barrier and are renally excreted [2, 7].",
    "Therapeutic Uses":"Hyperlipidemia, weight management, antidiabetic, anti-inflammatory, insomnia aid, cardiovascular and pulmonary support [2, 0, 2, 5].",
    "Side Effects":"Generally well tolerated; high doses may cause gastrointestinal upset and sedation [2, 4].",
    "Contraindications":"Pregnancy and lactation due to limited safety data; monitor blood sugar in diabetics [2, 2].",
    "Drug Interactions":"May potentiate hypoglycemic agents and anticoagulants; use caution when coadministered [2, 2].",
    "Toxicity":"Low; rodent LD50 for nuciferine >\u202f1000\u202fmg\/kg; minimal toxicity at dietary doses [2, 7].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Salvia divinorum",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Total dissociation, entity contact",
    "Preparation":"Smoked, intense, short duration",
    "Intensity":"High",
    "Onset":"1-5 min",
    "Legal Status":"Restricted in many regions",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \ud83c\udf00 Dissociation, \u26a0\ufe0f Restricted",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Absorbed via oral mucosa, smoking or vaporization; rapid onset (seconds\u2013minutes), short duration (~15\u201330\u202fmin), quickly metabolized to inactive salvinorin B [3, 1].",
    "Therapeutic Uses":"Visionary experiences in traditional Mazatec rituals; investigated for analgesic and anti-inflammatory properties [3, 0].",
    "Side Effects":"Tiredness, dizziness, amnesia, potential for transient psychosis in vulnerable individuals [3, 2].",
    "Contraindications":"Psychiatric disorders, cardiovascular instability; avoid in those at risk for psychosis [3, 2].",
    "Drug Interactions":"CNS depressants may potentiate sedative effects; caution when coadministered [3, 3].",
    "Toxicity":"Low toxicity; animal studies show minimal organ damage even at high doses [3, 3].",
    "Toxicity \/ LD50":"LD50 not established; salvinorin A active at microgram levels with no evidence of physical toxicity."
  },
  {
    "Herb":"Wild Lettuce",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Opium-like body high, sedation",
    "Preparation":"Smoke or extract",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":"Lactucin and lactucopicrin act as acetylcholinesterase inhibitors and may bind opioid receptors, producing sedative and analgesic effects [0, 50].",
    "Pharmacokinetics":"Oral ingestion (tea or tincture); onset 30\u201360\u202fmin; duration ~4\u202fh; metabolites excreted renally [0, 2].",
    "Therapeutic Uses":"Mild analgesic, sedative, sleep aid [0, 7].",
    "Side Effects":"Mydriasis, photophobia, dizziness, diaphoresis, auditory hallucinations, cardiovascular and respiratory distress at high doses [0, 2].",
    "Contraindications":"Pregnancy, concurrent sedative use, latex allergy.",
    "Drug Interactions":"Additive sedation with CNS depressants and alcohol.",
    "Toxicity":"Dose-dependent toxicity; hospitalizations reported but full recovery common [0, 2].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Valerian Root",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Deep sedation, dream fog",
    "Preparation":"Tea or tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Oral extracts: onset 30\u201360\u202fmin; constituents metabolized hepatically; half-life varies by preparation [4, 0].",
    "Therapeutic Uses":"Insomnia, nervous tension, mild anxiety; often combined with other sedatives for sleep disorders [4, 0].",
    "Side Effects":"Headache, stomach upset, vivid dreams, excitability; rare withdrawal symptoms upon abrupt discontinuation [4, 4].",
    "Contraindications":"Pregnancy, lactation; caution in those with hepatic impairment [4, 8].",
    "Drug Interactions":"Additive sedation with barbiturates, benzodiazepines, CNS depressants; may increase effects of amobarbital and phenobarbital [4, 7].",
    "Toxicity":"Low; occasional reports of hepatotoxicity, safe at therapeutic doses [4, 4].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Kava Kava",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Body numbing, mind floating",
    "Preparation":"Brewed tea (not smoked)",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal, restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83c\udf00 Dissociation, \u26a0\ufe0f Restricted",
    "Mechanism of Action":"Kavalactones such as kavain, methysticin, and yangonin modulate GABAA receptor activity and inhibit voltage-gated ion channels, producing anxiolytic, sedative, and muscle relaxant effects [1, 3, 1, 0].",
    "Pharmacokinetics":"Traditional aqueous extracts: onset 20\u201340\u202fmin; peak plasma kavalactone levels ~1\u20132\u202fh; extensively metabolized hepatically [1, 0].",
    "Therapeutic Uses":"Ceremonial and social drink in Pacific cultures for anxiety relief, muscle relaxation, and mild euphoria [1, 0].",
    "Side Effects":"Drowsiness, headache, gastrointestinal discomfort; potential hepatotoxicity with chronic use of non-water extracts [1, 0, 1, 6].",
    "Contraindications":"Liver disease, concurrent alcohol or hepatotoxic medications, pregnancy.",
    "Drug Interactions":"Additive sedation with alcohol and CNS depressants; caution with anticoagulants [1, 0].",
    "Toxicity":"Human LD50 unknown; animal studies indicate moderate safety margin; heavy chronic use linked to rare hepatotoxicity [1, 6].",
    "Toxicity \/ LD50":"Human LD50 unknown; animal studies indicate moderate safety margin; heavy chronic use linked to rare hepatotoxicity [1, 6]."
  },
  {
    "Herb":"Acorus calamus",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Mild hallucinations, odd clarity",
    "Preparation":"Tea or chewed (effects debated)",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Banned for food use in US (asarone)",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83d\udc8a Oral, \ud83c\udf00 Dissociation, \ud83e\udde0 Cognitive, \u2705 Safe",
    "Mechanism of Action":"Exhibits neuroprotective, antioxidant, antidepressant, and anticonvulsant effects, likely via modulation of GABAergic and monoaminergic systems [0, 10, 0, 15].",
    "Pharmacokinetics":"Oral administration: onset 30\u201360\u202fmin; peak plasma levels within 1\u20132\u202fh; metabolized hepatically and excreted renally [0, 15].",
    "Therapeutic Uses":"Traditional use as digestive tonic, neuroprotectant, and mood regulator; modern research explores antidepressant and anticonvulsant applications [0, 10].",
    "Side Effects":"Potential emmenagogic and genotoxic activity; avoid use due to carcinogenic \u03b2-asarone content [0, 0, 0, 5].",
    "Contraindications":"Pregnancy and lactation; use prohibited in some regions [0, 0].",
    "Drug Interactions":"None well documented; may reduce effectiveness of antacids [0, 25].",
    "Toxicity":"High doses linked to neurotoxicity; banned in some countries due to carcinogenic concerns [0, 0].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Chiric Sanango",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Shadow work, spiritual clearing",
    "Preparation":"Amazonian brew; not casual use",
    "Intensity":"High",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":"Contains \u03b2-carboline alkaloids (harmine, harmaline) and coumarins (scopoletin) that may inhibit monoamine oxidase and modulate serotonergic\/cholinergic systems [0, 11, 0, 1].",
    "Pharmacokinetics":"Traditionally infused or added to ayahuasca; alkaloids absorbed orally; onset ~30\u201360\u202fmin; duration several hours [0, 10].",
    "Therapeutic Uses":"Potentiates ayahuasca, used in Amazonian rituals for introspection and mild hallucinations [0, 4].",
    "Side Effects":"Dizziness, nausea, muscle tremors, delirium at high doses [0, 11].",
    "Contraindications":"Pregnancy, cardiovascular conditions.",
    "Drug Interactions":"Other serotonergic or cholinergic agents.",
    "Toxicity":"Toxic in high doses; caution advised.",
    "Toxicity \/ LD50":"LD50 not established; considered mildly toxic in large doses due to cholinergic effects."
  },
  {
    "Herb":"Wormwood",
    "Category":"Ritual \/ Visionary",
    "Effects":"Bittersweet trance, visual haze",
    "Preparation":"Used in absinthe or smoked with caution",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal, thujone regulated in some countries",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \ud83d\udd2e Ritual, \u2705 Safe",
    "Mechanism of Action":"Contains (\u2212)-\u03b1- and (+)-\u03b2-thujone, which act as GABAA receptor antagonists, causing mild convulsant and excitatory effects; also exhibits anti-inflammatory and antimicrobial properties [0, 3, 0, 22].",
    "Pharmacokinetics":"Oral use: onset 20\u201360\u202fmin; peak plasma thujone ~1\u20132\u202fh; metabolized by CYP450 enzymes [0, 22].",
    "Therapeutic Uses":"Digestive tonic, antiparasitic, antimicrobial, anti-inflammatory; ingredient in traditional absinthe liquor [0, 7].",
    "Side Effects":"Nausea, vomiting, convulsions, hallucinations at high doses; GI upset; allergic reactions [0, 3, 0, 22].",
    "Contraindications":"Pregnancy, epilepsy, seizure disorders, liver disease.",
    "Drug Interactions":"Additive neurotoxicity with other GABA antagonists; caution with CNS stimulants [0, 17].",
    "Toxicity":"Rodent oral LD50 for thujone ~45\u202fmg\/kg; chronic high intake associated with neurotoxicity [0, 3].",
    "Toxicity \/ LD50":"Rodent oral LD50 for thujone ~45\u202fmg\/kg; chronic high intake associated with neurotoxicity [0, 3]."
  },
  {
    "Herb":"Mexican Tarragon",
    "Category":"Other",
    "Effects":"Visionary clarity, spiritual herb",
    "Preparation":"Tea, incense, or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udd6f\ufe0f Ritual, \ud83e\udde0 Cognitive, \u2705 Safe",
    "Mechanism of Action":"Coumarins (dimethylfraxetin) and flavonoids modulate serotonergic (5-HT1A) and GABAergic (benzodiazepine binding) neurotransmission, producing anxiolytic and sedative-like effects [0, 0, 0, 4].",
    "Pharmacokinetics":"Aqueous infusions or tinctures: onset ~30\u201360\u202fmin; active coumarins undergo hepatic metabolism; excreted renally [0, 2].",
    "Therapeutic Uses":"Traditional antispasmodic, antidiarrheal, anxiolytic, sedative, and additive in tobacco mixtures for psychoactive effects [0, 0, 0, 5].",
    "Side Effects":"Drowsiness, nausea, headache in high doses [0, 1].",
    "Contraindications":"Pregnancy, lactation, respiratory conditions (smoking) [0, 0].",
    "Drug Interactions":"Potentiation of sedatives and MAO inhibitors [0, 2].",
    "Toxicity":"Low acute toxicity; no significant LD50 data available [0, 2].",
    "Toxicity \/ LD50":"Low acute toxicity; no significant LD50 data available [0, 2]."
  },
  {
    "Herb":"Frankincense",
    "Category":"Ritual \/ Visionary",
    "Effects":"Meditative trance, sacred space",
    "Preparation":"Resin incense",
    "Intensity":"Mild",
    "Onset":"5-20 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd6f\ufe0f Ritual, \ud83d\udd2e Ritual, \u2705 Safe",
    "Mechanism of Action":"Boswellic acids inhibit 5-lipoxygenase enzyme; anti-inflammatory and neuroprotective.",
    "Pharmacokinetics":"Oral extracts: peak plasma boswellic acids ~2\u202fh post-dose; hepatic metabolism; urinary excretion of metabolites [0, 12].",
    "Therapeutic Uses":"Anti-inflammatory for arthritis, ulcerative colitis, asthma; wound healing; cognitive support [0, 7, 0, 2].",
    "Side Effects":"GI upset, allergic reactions; rare hepatotoxicity [0, 7].",
    "Contraindications":"Pregnancy, bleeding disorders, surgery (increased bleeding risk) [0, 7].",
    "Drug Interactions":"Anticoagulants, immunosuppressants; may potentiate anti\u2011inflammatories [0, 7].",
    "Toxicity":"Generally well tolerated; high doses may cause stomach upset or hepatotoxicity in rare cases.",
    "Toxicity \/ LD50":"LD50 (boswellic acid) not well established; no known fatal dose in humans."
  },
  {
    "Herb":"Mapacho",
    "Category":"Ritual \/ Visionary",
    "Effects":"Sacred tobacco, heavy grounding",
    "Preparation":"Smoked ceremonially (very strong)",
    "Intensity":"High",
    "Onset":"1-5 min",
    "Legal Status":"Restricted (due to nicotine content)",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \ud83d\udd2e Ritual, \u26a0\ufe0f Restricted",
    "Mechanism of Action":"Nicotine agonizes nicotinic acetylcholine receptors; contains \u03b2-carbolines (harmala alkaloids) acting as reversible MAO inhibitors [1, 0, 1, 9].",
    "Pharmacokinetics":"Smoked or insufflated; rapid absorption via lungs or mucosa; peak plasma nicotine within minutes; half-life ~2\u202fhours [1, 0].",
    "Therapeutic Uses":"Shamanic entheogen in rap\u00e9 blends for sensory enhancement and ritual purification [1, 0].",
    "Side Effects":"Nausea, tachycardia, vomiting, dizziness at high doses [1, 0].",
    "Contraindications":"Cardiovascular disease, pregnancy.",
    "Drug Interactions":"Other nicotinic agonists and MAO inhibitors.",
    "Toxicity":"High risk of nicotine overdose; very toxic.",
    "Toxicity \/ LD50":"LD50 (nicotine) ~0.5\u20131.0 mg\/kg in humans (oral); overdose via smoke is rare but possible."
  },
  {
    "Herb":"Datura \/ Brugmansia",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Full blackout, dreamlike confusion",
    "Preparation":"NOT safe \u2013 toxic, unpredictable",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Dangerous \/ Toxic \/ Controlled",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"Antagonist at muscarinic acetylcholine receptors (M1\u2013M5); causes anticholinergic delirium.",
    "Pharmacokinetics":"Oral ingestion: onset 30\u201360\u202fmin; peak levels ~1\u20132\u202fh; extensively metabolized hepatically; excretion via urine [0, 0].",
    "Therapeutic Uses":"Historically used as antispasmodic, analgesic, and hypnotic; in modern medicine for motion sickness and as pre-anesthetic [0, 5].",
    "Side Effects":"Dry mouth, tachycardia, blurred vision, urinary retention, confusion, hallucinations; anticholinergic toxidrome at high doses [0, 15].",
    "Contraindications":"Glaucoma, prostatic hypertrophy, cardiovascular disease, psychiatric disorders, pregnancy [0, 5].",
    "Drug Interactions":"Additive anticholinergic effects with antihistamines, tricyclic antidepressants, antipsychotics [0, 5].",
    "Toxicity":"Extremely toxic; unpredictable alkaloid content (atropine, scopolamine) can cause fatal overdose.",
    "Toxicity \/ LD50":"Human LD50 (atropine) ~10 mg\/kg; child fatalities at ~50 seeds reported."
  },
  {
    "Herb":"Nutmeg (high dose)",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Dissociation, nausea, hallucinations",
    "Preparation":"Dangerous doses needed; not recommended",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Discouraged \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"Myristicin and elemicin exhibit mild hallucinogenic and anticholinergic effects by inhibiting acetylcholine receptors and monoamine oxidase [0, 21].",
    "Pharmacokinetics":"Oral ingestion: onset 3\u20136\u202fh; duration up to 12\u202fh; metabolized hepatically, excreted renally [0, 21].",
    "Therapeutic Uses":"Traditional deliriant, dream enhancement, aphrodisiac; flavoring agent in culinary contexts [0, 21].",
    "Side Effects":"Nausea, dry mouth, anxiety, delirium, hallucinations at psychoactive doses [0, 21].",
    "Contraindications":"Psychiatric disorders, liver disease, pregnancy [0, 21].",
    "Drug Interactions":"Additive CNS effects with depressants and MAOIs [0, 21].",
    "Toxicity":"Moderate-to-high toxicity at psychoactive doses; overdose risk for anticholinergic delirium [0, 21].",
    "Toxicity \/ LD50":"Estimated LD50 (myristicin) ~5600 mg\/kg in rats; toxic threshold in humans ~5g+ of nutmeg powder."
  },
  {
    "Herb":"Asparagus racemosus (Shatavari)",
    "Category":"Other",
    "Effects":"Spiritual dreaming, subtle energy shifts",
    "Preparation":"Tea or tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable, \u2705 Safe",
    "Mechanism of Action":"Steroidal saponins (shatavarins) modulate estrogen receptors and exhibit antioxidant, immunomodulatory, and neuroprotective properties [1, 4].",
    "Pharmacokinetics":"Oral administration: onset 30\u201360\u202fmin; bioactive saponins have prolonged half-life; cumulative effects with daily dosing [1, 4].",
    "Therapeutic Uses":"Galactagogue, reproductive health support, adaptogen for stress, gastric ulcer treatment, diuretic [1, 5].",
    "Side Effects":"GI upset, headache; potential hormonal effects at high doses [1, 5].",
    "Contraindications":"Pregnancy (high doses), hormone-sensitive cancers; caution with hypoglycemic agents [0, 3].",
    "Drug Interactions":"Lithium (efficacy reduction) and hypoglycemic drugs; possible additive effects [0, 3].",
    "Toxicity":"Low toxicity; very high doses may induce convulsions in animal models; generally well-tolerated [1, 9].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Tagetes lucida (Mexican Tarragon)",
    "Category":"Other",
    "Effects":"Visionary dreams, clarity",
    "Preparation":"Tea, incense, or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udd6f\ufe0f Ritual, \ud83e\udde0 Cognitive, \u2705 Safe",
    "Mechanism of Action":"Coumarins (dimethylfraxetin, herniarin) and essential oils (methyl eugenol, estragole) interact with GABA\u2090 and 5-HT\u2081\u2090 receptors, producing anxiolytic and sedative effects [2, 2, 2, 10].",
    "Pharmacokinetics":"Consumed as tea or tincture; onset ~20\u201330\u202fmin; duration ~2\u20134\u202fhours [2, 2].",
    "Therapeutic Uses":"Anxiolytic, digestive aid, ritual incense for purification [2, 10].",
    "Side Effects":"Mild GI upset, potential photosensitivity [2, 3].",
    "Contraindications":"Pregnancy, concurrent sedatives.",
    "Drug Interactions":"Benzodiazepines and serotonergic drugs.",
    "Toxicity":"Low; traditional use generally safe.",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Turnera diffusa",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Same as Damiana \u2013 aphrodisiac, mood lift",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udcab Euphoria, \u2705 Safe",
    "Mechanism of Action":"Likely modulates serotonin, dopamine, and GABA neurotransmission via flavonoids and tannins [8, 6].",
    "Pharmacokinetics":"Tea or smoked; onset ~30\u201345\u202fmin; duration ~2\u20134\u202fhours [8, 6].",
    "Therapeutic Uses":"Aphrodisiac, mood enhancement, stress relief [8, 6].",
    "Side Effects":"Mild headache, insomnia at high doses [8, 6].",
    "Contraindications":"Pregnancy, MAOI coadministration.",
    "Drug Interactions":"Serotonergic medications.",
    "Toxicity":"Low in traditional doses.",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Kratom (Mitragyna speciosa)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Stimulant or sedative euphoria (dose-dependent)",
    "Preparation":"Oral only \u2013 not smoked",
    "Intensity":"High",
    "Onset":"1-5 min",
    "Legal Status":"Restricted in some regions",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \ud83d\udc8a Oral, \ud83d\udcab Euphoria, \u26a1 Stimulant, \u26a0\ufe0f Restricted",
    "Mechanism of Action":"Mitragynine and 7-hydroxymitragynine act as partial agonists at \u03bc-opioid receptors, and interact with adrenergic and serotonergic systems [0, 9].",
    "Pharmacokinetics":"Oral: onset 15\u201345\u202fmin; duration 3\u20136\u202fh; hepatic metabolism via CYP enzymes; excretion renal [0, 9].",
    "Therapeutic Uses":"Analgesic, mood enhancer, stimulant or sedative (dose-dependent), opioid withdrawal management [0, 9].",
    "Side Effects":"Constipation, nausea, dependency risk, dizziness [0, 9].",
    "Contraindications":"Pregnancy, liver or kidney impairment, concurrent opioid or CNS depressant use [0, 9].",
    "Drug Interactions":"Additive sedation with opioids and sedatives; caution with MAOIs [0, 9].",
    "Toxicity":"Low-to-moderate; overdose may cause respiratory depression and death [0, 9].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Kra Thum Na \/ Kok",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Stimulation, kratom-like body feel",
    "Preparation":"Capsule or tea",
    "Intensity":"Moderate",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83d\udc8a Oral, \ud83d\udcab Euphoria, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Sakae Naa",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mild stimulant, mood separation",
    "Preparation":"Tea or capsule",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83d\udc8a Oral, \ud83d\udcab Euphoria, \u26a1 Stimulant, \u2705 Safe",
    "Mechanism of Action":"Mitragynine-like alkaloids; mild adrenergic and dopaminergic stimulation.",
    "Pharmacokinetics":"Oral (tea\/capsule); onset 20\u201340 min; effects last ~3\u20134 hrs.",
    "Therapeutic Uses":"Used as stimulant, mood enhancer, and mild analgesic.",
    "Side Effects":"Mild stimulation, jitteriness, GI upset at high doses.",
    "Contraindications":"Avoid with stimulants or heart issues.",
    "Drug Interactions":"May interact with MAOIs, stimulants, and certain SSRIs.",
    "Toxicity":"Low, but less studied than kratom.",
    "Toxicity \/ LD50":"Not established; no fatalities reported in isolated use."
  },
  {
    "Herb":"Nelumbo nucifera",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mild dissociation, calm euphoria",
    "Preparation":"Tea, smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal, low concern",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udcab Euphoria, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Contains nuciferine (dopamine receptor modulator) and aporphine alkaloids.",
    "Pharmacokinetics":"Smoked or tea; onset rapid (5\u201315 min); duration ~2\u20133 hrs.",
    "Therapeutic Uses":"Mild euphoria, stress reduction, dream enhancement.",
    "Side Effects":"Mild dizziness or nausea if overused.",
    "Contraindications":"Pregnancy, hypotension.",
    "Drug Interactions":"Possible additive effects with MAOIs and dopamine agents.",
    "Toxicity":"Low toxicity in traditional doses.",
    "Toxicity \/ LD50":"Not well-established; estimated to be >500 mg\/kg (safe range)."
  },
  {
    "Herb":"Scullcap (Scutellaria)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Relaxing, anxiety-reducing, dream support",
    "Preparation":"Tea or tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":"Flavonoids and baicalin modulate GABA-A receptors and inhibit inflammation.",
    "Pharmacokinetics":"Taken orally; onset ~30 min; effects last ~2\u20134 hrs.",
    "Therapeutic Uses":"Calming, anticonvulsant, neuroprotective.",
    "Side Effects":"Rarely causes liver enzyme elevation or drowsiness.",
    "Contraindications":"Liver issues; consult provider before long-term use.",
    "Drug Interactions":"Additive effects with sedatives or anxiolytics.",
    "Toxicity":"Generally safe, though adulterants in supplements have caused concern.",
    "Toxicity \/ LD50":"No standard LD50 data; high therapeutic margin."
  },
  {
    "Herb":"California Poppy",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Gentle sedative, dreamlike calm",
    "Preparation":"Tea, tincture, or extract",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Mild GABAergic activity and opioid receptor affinity (non-narcotic).",
    "Pharmacokinetics":"Oral (tea or tincture); onset ~30 min; lasts 2\u20133 hrs.",
    "Therapeutic Uses":"Used for anxiety, insomnia, and pain management.",
    "Side Effects":"Drowsiness, vivid dreams, dizziness.",
    "Contraindications":"Not for use in pregnancy or with other CNS depressants.",
    "Drug Interactions":"May amplify effects of benzodiazepines and alcohol.",
    "Toxicity":"Low toxicity; non-habit-forming.",
    "Toxicity \/ LD50":"No known LD50 in humans; safe at standard doses."
  },
  {
    "Herb":"Hop Flowers",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Relaxation, dream enhancement",
    "Preparation":"Tea or herbal pillow",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":"Binds to GABA-A receptors, promoting sedation and relaxation.",
    "Pharmacokinetics":"Oral or inhaled; onset ~20\u201340 min; duration ~2\u20134 hrs.",
    "Therapeutic Uses":"Used as a mild sleep aid, anxiety reducer, and dream enhancer.",
    "Side Effects":"Drowsiness, mild headache, possible hormonal effects in large doses.",
    "Contraindications":"Pregnancy, estrogen-sensitive conditions (e.g. breast cancer).",
    "Drug Interactions":"May enhance sedatives, alcohol, and hypnotics.",
    "Toxicity":"Very low toxicity; generally regarded as safe.",
    "Toxicity \/ LD50":"No human LD50; high safety margin reported in herbal use."
  },
  {
    "Herb":"Copal",
    "Category":"Ritual \/ Visionary",
    "Effects":"Purifying, sacred aroma, trance enhancement",
    "Preparation":"Burned as incense",
    "Intensity":"Mild",
    "Onset":"5-20 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd6f\ufe0f Ritual, \ud83d\udd2e Ritual, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Sweetgrass",
    "Category":"Ritual \/ Visionary",
    "Effects":"Positive energy, spiritual invocation",
    "Preparation":"Burned or braided for ceremonies",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd2e Ritual, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"White Sage",
    "Category":"Ritual \/ Visionary",
    "Effects":"Clarity, purification, spiritual reset",
    "Preparation":"Burned as incense",
    "Intensity":"Mild",
    "Onset":"5-20 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd6f\ufe0f Ritual, \ud83d\udd2e Ritual, \ud83e\udde0 Cognitive, \u2705 Safe",
    "Mechanism of Action":"1,8-Cineole and \u03b1-thujone inhibit pro-inflammatory cytokines (TNF\u03b1, IL-1\u03b2) and arachidonic acid metabolism; antimicrobial and antiviral effects via NF-\u03baB inhibition [0, 19, 0, 4].",
    "Pharmacokinetics":"Inhaled or topical; rapid local absorption; systemic exposure minimal; metabolites excreted renally [0, 4].",
    "Therapeutic Uses":"Smudging rituals for purification, antimicrobial, respiratory support, mental clarity [0, 19].",
    "Side Effects":"Respiratory irritation, asthmatic exacerbation, headaches at high exposure [0, 19].",
    "Contraindications":"Asthma, pregnancy, respiratory disorders.",
    "Drug Interactions":"None significant documented.",
    "Toxicity":"Very low; excessive inhalation may cause dizziness or nausea [0, 4].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Frankincense (Boswellia)",
    "Category":"Other",
    "Effects":"Trance, meditative awareness",
    "Preparation":"Resin burned",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Henbane",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Delirium, hallucinations, anticholinergic",
    "Preparation":"Historically ritual; dangerous\/toxic",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Controlled \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83d\udd6f\ufe0f Ritual, \u2620\ufe0f Toxic",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Belladonna",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Hallucinations, dreamlike confusion",
    "Preparation":"Highly toxic \u2013 not for casual use",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Controlled \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"Tropane alkaloids block acetylcholine; causes anticholinergic delirium.",
    "Pharmacokinetics":"Oral or topical; onset ~30\u201390 mins; effects last 4\u201312 hrs.",
    "Therapeutic Uses":"Historically used for pain, muscle spasms, and cosmetic dilation.",
    "Side Effects":"Dry mouth, hallucinations, delirium, elevated pulse.",
    "Contraindications":"Cardiovascular disease, glaucoma, pregnancy.",
    "Drug Interactions":"CNS depressants, anticholinergic drugs.",
    "Toxicity":"Highly toxic; accidental ingestion can be fatal.",
    "Toxicity \/ LD50":"Atropine LD50 (rat, oral): ~453 mg\/kg."
  },
  {
    "Herb":"Mandrake Root",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Narcotic, visionary trance",
    "Preparation":"Traditional ceremonial use only",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Controlled \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"Contains tropane alkaloids (scopolamine, atropine); anticholinergic deliriant.",
    "Pharmacokinetics":"Oral or transdermal; slow absorption; long-lasting (6\u201312 hrs).",
    "Therapeutic Uses":"Historically used as anesthetic, antispasmodic, and in witchcraft.",
    "Side Effects":"Dry mouth, confusion, hallucinations, elevated heart rate.",
    "Contraindications":"Pregnancy, glaucoma, heart conditions.",
    "Drug Interactions":"Potentiates other anticholinergics, CNS depressants.",
    "Toxicity":"Highly toxic in moderate doses.",
    "Toxicity \/ LD50":"Scopolamine LD50 (rat, oral): ~310 mg\/kg."
  },
  {
    "Herb":"Anadenanthera peregrina (Yopo)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Powerful snuff, DMT-like visuals",
    "Preparation":"Prepared as snuff (contains bufotenine)",
    "Intensity":"High",
    "Onset":"1-3 min",
    "Legal Status":"Restricted in many regions",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Bufotenin in the seeds functions as a non-selective serotonin receptor agonist and serotonin releasing agent [1, 1].",
    "Pharmacokinetics":"Insufflated snuff: rapid onset; typical dose contains ~40\u202fmg bufotenin from ~0.5\u202fg seeds; rodent LD50 ~200\u2013300\u202fmg\/kg [1, 1].",
    "Therapeutic Uses":"Used ceremonially as cohoba\/yopo snuff for entheogenic experiences [1, 1].",
    "Side Effects":"Tachycardia, facial flushing, respiratory difficulty, leg cramps, nausea, vomiting [1, 1].",
    "Contraindications":"Cardiovascular disease, psychiatric disorders, pregnancy.",
    "Drug Interactions":"Serotonergic medications may potentiate effects.",
    "Toxicity":"High concentrations potentially embryotoxic and angiogenic; human toxicity data limited.",
    "Toxicity \/ LD50":"Bufotenin LD50 (mice, intraperitoneal): ~200\u2013300 mg\/kg; relatively safe at ritual doses."
  },
  {
    "Herb":"Anadenanthera colubrina (Ceb\u00edl)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Entheogenic snuff, alternate reality feel",
    "Preparation":"South American use",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Restricted in many regions",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Bufotenin acts as a potent and non-selective serotonin receptor agonist at 5-HT\u2081A, 5-HT\u2082A, 5-HT\u2082C, and 5-HT\u2083 receptors, and serves as a specific serotonin releasing agent [1, 0].",
    "Pharmacokinetics":"When insufflated, bufotenin is rapidly absorbed nasally with onset in 5\u201315\u202fmin and duration around 1\u20132\u202fh [1, 1].",
    "Therapeutic Uses":"Traditionally used as a snuff for visionary and divinatory rituals in South American cultures [1, 1].",
    "Side Effects":"Prominent cardiovascular changes, nausea, vomiting, and dizziness [1, 0, 1, 1].",
    "Contraindications":"Cardiovascular disorders, psychiatric conditions, and pregnancy.",
    "Drug Interactions":"Concomitant use with SSRIs or MAOIs may risk serotonin syndrome [1, 0].",
    "Toxicity":"No documented human LD50; rodent LD50 approximately 200\u2013300\u202fmg\/kg (intraperitoneal) [1, 0].",
    "Toxicity \/ LD50":"No documented human LD50; rodent LD50 approximately 200\u2013300\u202fmg\/kg (intraperitoneal) [1, 0]."
  },
  {
    "Herb":"Virola spp.",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"DMT-containing tree resin",
    "Preparation":"Used in Amazonian snuffs",
    "Intensity":"High",
    "Onset":"1-3 min",
    "Legal Status":"Restricted \/ Controlled",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Contains DMT, 5-MeO-DMT, and beta-carbolines; classic tryptamine entheogen profile.",
    "Pharmacokinetics":"Insufflated or oral with MAOIs; fast onset if smoked or snuffed.",
    "Therapeutic Uses":"Used in Amazonian shamanic healing rituals; possible antidepressant potential.",
    "Side Effects":"Nausea, intense hallucinations, elevated heart rate.",
    "Contraindications":"Mental health disorders, heart issues, MAOI interactions.",
    "Drug Interactions":"Dangerous with SSRIs, MAOIs, and other serotonergic substances.",
    "Toxicity":"Can be overwhelming; physical toxicity low but psychological risks high.",
    "Toxicity \/ LD50":"No established LD50 for DMT in humans; low systemic toxicity at typical doses."
  },
  {
    "Herb":"Acorus gramineus",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Cognitive clarity, trippy effects (debated)",
    "Preparation":"Tea or chewed",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udde8\ud83c\uddf3 East Asia",
    "Tags":"\u2615 Brewable, \ud83d\udc8a Oral, \ud83e\udde0 Cognitive, \u2705 Safe",
    "Mechanism of Action":"Contains \u03b2-asarone; may modulate acetylcholine and GABA pathways; traditional use for cognition.",
    "Pharmacokinetics":"Oral tea or tincture; slow onset (~1 hr); mild duration (2\u20133 hrs).",
    "Therapeutic Uses":"Cognitive enhancement, anxiety, neuroprotective potential.",
    "Side Effects":"Nausea at high doses, possible carcinogenic risk with long-term \u03b2-asarone exposure.",
    "Contraindications":"Pregnancy, long-term use caution due to \u03b2-asarone.",
    "Drug Interactions":"May enhance CNS depressants.",
    "Toxicity":"Concerns over \u03b2-asarone carcinogenicity in some studies.",
    "Toxicity \/ LD50":"\u03b2-asarone LD50 (rat, oral): ~310 mg\/kg."
  },
  {
    "Herb":"Celastrus paniculatus (Intellect Tree)",
    "Category":"Other",
    "Effects":"Lucid dreaming, cognitive enhancer",
    "Preparation":"Oil or seeds consumed",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83e\udde0 Cognitive, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Silphium (extinct)",
    "Category":"Other",
    "Effects":"Ancient psychoactive\/contraceptive herb",
    "Preparation":"No longer available but worth note",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Nymphaea ampla",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Sedative, euphoric, dreamlike states",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udcab Euphoria, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Pedicularis densiflora (Indian warrior)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Muscle relaxation, mild body high",
    "Preparation":"Smoked or tea",
    "Intensity":"Moderate",
    "Onset":"5-15 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa, \ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":"Muscle relaxant potential via GABAergic modulation [2, 0].",
    "Pharmacokinetics":"Smoked or tea; onset rapid (minutes); duration ~2\u20133\u202fh [2, 0].",
    "Therapeutic Uses":"Muscle tension, pain relief, sleep aid applications [2, 0].",
    "Side Effects":"Drowsiness, dizziness [2, 0].",
    "Contraindications":"Pregnancy, use with other sedatives [2, 0].",
    "Drug Interactions":"Additive effects with CNS depressants [2, 0].",
    "Toxicity":"Low; limited data on long-term use [2, 0].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Pedicularis groenlandica",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Stronger relaxation, tension relief",
    "Preparation":"Smoked or tea",
    "Intensity":"Moderate",
    "Onset":"5-15 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83c\udf00 Dissociation, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Oral infusion onset ~30\u202fmin; duration ~4\u202fh; metabolites excreted renally [0, 7].",
    "Therapeutic Uses":"Muscle relaxant, antioxidant, antimicrobial, traditional remedy for pain and inflammation [0, 7].",
    "Side Effects":"Rare; possible GI upset [0, 7].",
    "Contraindications":"Pregnancy, lactation [0, 7].",
    "Drug Interactions":"Additive with CNS depressants [0, 7].",
    "Toxicity":"Low; no significant toxicity reported [0, 7].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Lactuca canadensis",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Wild lettuce relative, opium-like calm",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83c\udf00 Dissociation, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Contains lactucopicrin and lactucin; thought to act as mild opioid receptor agonists.",
    "Pharmacokinetics":"Oral ingestion onset 30\u201360\u202fmin; duration ~4\u202fh; metabolites excreted renally [0, 6].",
    "Therapeutic Uses":"Sedative, analgesic, sleep aid, antitussive [0, 6].",
    "Side Effects":"Mydriasis, dizziness, GI upset at high doses [0, 6].",
    "Contraindications":"Pregnancy, concurrent opioid use [0, 6].",
    "Drug Interactions":"CNS depressants [0, 6].",
    "Toxicity":"Low; hospitalizations reported but recovery common [0, 6].",
    "Toxicity \/ LD50":"Not established; presumed low. No acute toxicity reported in human use."
  },
  {
    "Herb":"Artemisia absinthium (Wormwood)",
    "Category":"Ritual \/ Visionary",
    "Effects":"Trance states, dream-like visuals",
    "Preparation":"Tea or smoke",
    "Intensity":"Moderate",
    "Onset":"15-45 min",
    "Legal Status":"Legal, thujone regulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udd2e Ritual, \u2705 Safe",
    "Mechanism of Action":"Contains (\u2212)-\u03b1- and (+)-\u03b2-thujone, potent GABA\u2090 receptor antagonists; also exhibits anti-inflammatory, antimicrobial, antioxidant, and MAO-inhibitory activities [1, 3, 0, 7].",
    "Pharmacokinetics":"Oral use: onset 20\u201360\u202fmin; peak plasma levels ~1\u20132\u202fh; systemic distribution of active constituents [0, 22].",
    "Therapeutic Uses":"Digestive tonic, Crohn's disease aid, antiparasitic, antimicrobial, and anti-inflammatory agent [0, 7].",
    "Side Effects":"High-dose thujone can cause convulsions, insomnia, and hallucinations; GI upset; allergic reactions [1, 3, 0, 7].",
    "Contraindications":"Pregnancy, epilepsy, seizure disorders, liver disease; avoid in children [0, 7].",
    "Drug Interactions":"Increases INR with warfarin; additive CNS depression with sedatives and MAOIs [1, 3].",
    "Toxicity":"Rodent LD50 for thujone ~45\u202fmg\/kg; chronic overuse linked to neurotoxicity and convulsions [1, 3].",
    "Toxicity \/ LD50":"Rodent LD50 for thujone ~45\u202fmg\/kg; chronic overuse linked to neurotoxicity and convulsions [1, 3]."
  },
  {
    "Herb":"Artemisia vulgaris (Mugwort)",
    "Category":"Oneirogen",
    "Effects":"Lucid dreaming, light hallucinations",
    "Preparation":"Smoke, tea, or ritual incense",
    "Intensity":"Mild",
    "Onset":"5-15 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udd6f\ufe0f Ritual, \ud83e\udde0 Dream, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Justicia pectoralis",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Aromatic, mild euphoria, anti-anxiety",
    "Preparation":"Smoked or brewed",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83d\udcab Euphoria, \u2705 Safe",
    "Mechanism of Action":"Contains coumarin and umbelliferone; mild monoamine modulation; relaxant properties.",
    "Pharmacokinetics":"Oral infusion onset 30\u201360\u202fmin; metabolites via hepatic pathways; urinary excretion [0, 10].",
    "Therapeutic Uses":"Gastroprotective, anti-inflammatory, antispasmodic, anxiolytic; used as snuff admixture [0, 2, 0, 10].",
    "Side Effects":"Rare; possible sedation, GI discomfort [0, 10].",
    "Contraindications":"Pregnancy; MAOI coadministration [0, 18].",
    "Drug Interactions":"MAO inhibitors, sedatives [0, 18].",
    "Toxicity":"Low; safe at traditional doses [0, 10].",
    "Toxicity \/ LD50":"Low; no established LD50, but considered safe in traditional use."
  },
  {
    "Herb":"Viola odorata (Sweet violet)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Mild sedative, calming, gentle dreaminess",
    "Preparation":"Tea or syrup",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Mild central sedative via salicylates and alkaloids; may influence serotonin and prostaglandin pathways.",
    "Pharmacokinetics":"Taken as tea or syrup; onset ~30 min; short duration.",
    "Therapeutic Uses":"Cough suppressant, mild anxiolytic, anti-inflammatory, gentle sleep aid.",
    "Side Effects":"Very rare; may include mild drowsiness or nausea.",
    "Contraindications":"None known in normal amounts; avoid if allergic.",
    "Drug Interactions":"Minimal; theoretically additive with CNS depressants.",
    "Toxicity":"Regarded as very safe in traditional herbalism.",
    "Toxicity \/ LD50":"No human LD50 data; extremely low toxicity reported."
  },
  {
    "Herb":"Piper auritum (Root beer plant)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Calming, warming, euphoric",
    "Preparation":"Tea or culinary use",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83d\udcab Euphoria, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Contains safrole and other volatile oils; possible mild dopaminergic stimulation and GI modulation.",
    "Pharmacokinetics":"Oral infusion or extract onset 30\u201360\u202fmin; hepatic metabolism; renal excretion [0, 11].",
    "Therapeutic Uses":"Digestive aid, anti-inflammatory, antimutagen, diuretic, antipyretic [0, 11].",
    "Side Effects":"High doses may cause GI upset; safrole is a potential carcinogen [1, 11].",
    "Contraindications":"Pregnancy; safrole-containing extracts discouraged [1, 11].",
    "Drug Interactions":"CYP450 substrates; caution with anticoagulants [0, 19].",
    "Toxicity":"Safrole hepatotoxic; use sparingly [1, 11].",
    "Toxicity \/ LD50":"LD50 (rats, oral) safrole ~1,950 mg\/kg; safrole is hepatotoxic at high doses."
  },
  {
    "Herb":"Eschscholzia californica (California poppy)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Sleep aid, mild dreamlike calm",
    "Preparation":"Tea, tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Oral (tea, extract); onset 30\u201360\u202fmin; duration ~4\u202fh; bioavailability of key alkaloids moderate [2, 3].",
    "Therapeutic Uses":"Anxiety reduction, insomnia aid, mild analgesic, vasomotor headache relief [2, 3, 2, 7].",
    "Side Effects":"High doses may cause residual sedation (\"hangover\"), nausea, dizziness; avoid operating machinery [2, 8, 2, 9].",
    "Contraindications":"Glaucoma, MAOI therapy, pregnancy, lactation [2, 9].",
    "Drug Interactions":"Additive CNS depression with sedatives, barbiturates; caution with blood thinners and antihypertensives [2, 8].",
    "Toxicity":"Low; no significant toxicity at therapeutic doses [2, 9].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Rivea corymbosa",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Dreamy visuals, nausea, traditional Mazatec use",
    "Preparation":"Seeds ground and cold infused",
    "Intensity":"High",
    "Onset":"30-90 min",
    "Legal Status":"Restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Insufflated or ingested; onset 20\u201360\u202fmin; duration 4\u20138\u202fh; hepatic metabolism [0, 12].",
    "Therapeutic Uses":"Entheogenic snuff (ololiuqui) in Mesoamerican rituals [0, 4].",
    "Side Effects":"Nausea, vasoconstriction, dizziness [0, 4].",
    "Contraindications":"Cardiovascular disease, pregnancy [0, 4].",
    "Drug Interactions":"Serotonergic medications [0, 12].",
    "Toxicity":"Low; moderate overdose risk [0, 12].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Ipomoea tricolor (Heavenly Blue)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"LSD-like visuals, spiritual confusion",
    "Preparation":"Seeds ground and cold infused",
    "Intensity":"High",
    "Onset":"30-90 min",
    "Legal Status":"Restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Oral ingestion onset 45\u2013120\u202fmin; duration 4\u201310\u202fh; hepatic metabolism [0, 5].",
    "Therapeutic Uses":"Visionary experiences, ethnobotanical use [0, 5].",
    "Side Effects":"Nausea, vasoconstriction, headache [0, 5].",
    "Contraindications":"Cardiovascular disorders, psychiatric conditions [0, 5].",
    "Drug Interactions":"SSRIs\/MAOIs [0, 5].",
    "Toxicity":"Low; rodent LD50 ~200\u2013300\u202fmg\/kg [0, 5].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Argyreia nervosa (Hawaiian Baby Woodrose)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Visionary, sedative, nausea-prone",
    "Preparation":"Cold water seed infusion",
    "Intensity":"High",
    "Onset":"30-90 min",
    "Legal Status":"Restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Seeds contain ergolines (ergine\/LSA and isoergine) acting as partial agonists at 5-HT\u2082A serotonin receptors and dopamine receptors, producing mild psychedelic effects [1, 2, 1, 7].",
    "Pharmacokinetics":"Oral ingestion: onset 20\u2013180\u202fmin; peak ~2\u202fh; duration 4\u201310\u202fh [1, 2].",
    "Therapeutic Uses":"Traditional entheogen in Mesoamerican rituals and modern recreational use [1, 2].",
    "Side Effects":"Nausea, vomiting, vasoconstriction, dizziness, sedation [1, 2].",
    "Contraindications":"Cardiovascular disorders, psychiatric conditions, pregnancy.",
    "Drug Interactions":"CNS depressants and serotonergic agents may enhance effects.",
    "Toxicity":"No known human fatalities; rodent LD50 for ergine ~200\u2013300\u202fmg\/kg.",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Tilia europaea (Linden flower)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Calming, relaxing, mild dream aid",
    "Preparation":"Tea",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\u2615 Brewable, \ud83c\udf00 Dissociation, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":null,
    "Therapeutic Uses":null,
    "Side Effects":null,
    "Contraindications":null,
    "Drug Interactions":null,
    "Toxicity":null,
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Melissa officinalis (Lemon balm)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Anxiolytic, cognitive calming",
    "Preparation":"Tea, tincture, or smoke",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable, \u2615 Brewable, \ud83c\udf00 Dissociation, \ud83e\udde0 Cognitive, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":null,
    "Pharmacokinetics":"Oral onset 30\u201360\u202fmin; active compounds absorbed in GI tract; hepatic metabolism; renal excretion [0, 0].",
    "Therapeutic Uses":"Anxiety, insomnia, nervous tension, digestive aid [0, 8].",
    "Side Effects":"Drowsiness; possible allergic reactions; GI upset at high doses [0, 0].",
    "Contraindications":"Pregnancy, known Asteraceae allergy [0, 16].",
    "Drug Interactions":"May potentiate sedatives, anticoagulants; caution with CNS depressants [0, 16].",
    "Toxicity":"Low; safe at therapeutic doses [0, 0].",
    "Toxicity \/ LD50":null
  },
  {
    "Herb":"Ocimum sanctum (Holy Basil \/ Tulsi)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mood lift, sacred calm, spiritual focus",
    "Preparation":"Tea or incense",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable, \ud83d\udd6f\ufe0f Ritual, \ud83d\udcab Euphoria, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Modulates cortisol, inflammation, and neurotransmitters; contains eugenol, ursolic acid, and apigenin.",
    "Pharmacokinetics":"Rapid absorption via oral tea\/tincture; hepatic metabolism.",
    "Therapeutic Uses":"Adaptogen, anxiety, spiritual focus, blood sugar balance.",
    "Side Effects":"May lower blood sugar, mild sedation, mild nausea.",
    "Contraindications":"Pregnancy, diabetes medication.",
    "Drug Interactions":"May potentiate anti-diabetic, anticoagulant, or sedative drugs.",
    "Toxicity":"Pending",
    "Toxicity \/ LD50":"Pending"
  },
  {
    "Herb":"Rhodiola rosea",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Focus, reduced fatigue, mind clarity",
    "Preparation":"Capsule, tincture",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83d\udc8a Oral, \ud83d\udcab Euphoria, \ud83e\udde0 Cognitive, \u2705 Safe",
    "Mechanism of Action":"Influences serotonin, norepinephrine, dopamine; modulates HPA axis and stress adaptation via rosavins and salidroside.",
    "Pharmacokinetics":"Absorbed orally; peak plasma ~1-2 hours; active compounds metabolized in liver, excreted renally.",
    "Therapeutic Uses":"Fatigue, stress resilience, cognitive enhancement, mild depression.",
    "Side Effects":"Irritability, dry mouth, dizziness (rare, dose-dependent).",
    "Contraindications":"Bipolar disorder, stimulants, pregnancy.",
    "Drug Interactions":"May affect antidepressants, stimulants, or MAOIs.",
    "Toxicity":"Mild toxicity; high doses may cause irritability or insomnia.",
    "Toxicity \/ LD50":"LD50 (rats, oral) >28,000 mg\/kg; very low toxicity."
  },
  {
    "Herb":"Withania somnifera (Ashwagandha)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Grounded calm, dream support",
    "Preparation":"Tea or capsule",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable, \ud83d\udc8a Oral, \ud83c\udf00 Dissociation, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Modulates GABAergic and serotonergic activity; reduces cortisol; withanolides are primary active compounds.",
    "Pharmacokinetics":"Oral onset 30\u201360\u202fmin; withanolides bioavailable; hepatic metabolism; renal excretion [0, 17].",
    "Therapeutic Uses":"Adaptogen, anti-stress, anxiolytic, neuroprotective, anti-inflammatory, immune support [0, 1, 0, 17].",
    "Side Effects":"GI upset, drowsiness, rare thyroid hormone changes [0, 9].",
    "Contraindications":"Pregnancy, hyperthyroidism, autoimmune diseases [0, 1].",
    "Drug Interactions":"Immunosuppressants, sedatives, thyroid medications [0, 24].",
    "Toxicity":"Low; well-tolerated in clinical studies [0, 1].",
    "Toxicity \/ LD50":"LD50 (rats, oral) ~4650 mg\/kg; relatively low acute toxicity."
  },
  {
    "Herb":"Bacopa monnieri",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Memory enhancer, mild calming",
    "Preparation":"Tea, capsule",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable, \ud83d\udc8a Oral, \ud83d\udcab Euphoria, \ud83e\uddd8 Sedation, \u2705 Safe",
    "Mechanism of Action":"Contains bacosides A and B which enhance cholinergic transmission, antioxidant defenses, and modulate neurotransmitter levels (serotonin, dopamine) [0, 0, 0, 2].",
    "Pharmacokinetics":"Oral preparations (extracts or powder); onset 30\u201360\u202fmin; requires chronic dosing for peak cognitive benefits [0, 5].",
    "Therapeutic Uses":"Cognitive enhancement (memory, learning), anxiety reduction, ADHD management [0, 1, 0, 6].",
    "Side Effects":"Gastrointestinal upset (nausea, increased motility), fatigue, dry mouth [0, 5].",
    "Contraindications":"Pregnancy, lactation, hypersensitivity to any component [0, 5].",
    "Drug Interactions":"No major interactions documented; caution with sedatives [0, 5].",
    "Toxicity":"Generally non-toxic; no serious adverse effects at recommended doses; rodent LD50 not well established [0, 6].",
    "Toxicity \/ LD50":"Generally non-toxic; no serious adverse effects at recommended doses; rodent LD50 not well established [0, 6]."
  },
  {
    "Herb":"Eleutherococcus senticosus (Siberian Ginseng)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Balanced energy, mood resilience",
    "Preparation":"Tea or extract",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udde8\ud83c\uddf3 East Asia",
    "Tags":"\u2615 Brewable, \ud83d\udcab Euphoria, \u2705 Safe",
    "Mechanism of Action":"Adaptogenic modulation of HPA axis and immune response; contains eleutherosides influencing stress resilience.",
    "Pharmacokinetics":"Oral onset in 30\u201360 minutes; active glycosides metabolized hepatically.",
    "Therapeutic Uses":"Fatigue, immune support, cognitive performance under stress.",
    "Side Effects":"Mild insomnia, irritability, nervousness in high doses.",
    "Contraindications":"Hypertension, pregnancy, hormone-sensitive conditions.",
    "Drug Interactions":"May interact with stimulants, immunosuppressants, and anticoagulants.",
    "Toxicity":"Generally considered safe when used short-term. Long-term effects less studied.",
    "Toxicity \/ LD50":"No established LD50; high doses in animals show minimal acute toxicity."
  }
];