const herbData = [
  {
    "Herb":"Calea zacatechichi",
    "Category":"Oneirogen",
    "Effects":"Vivid\/lucid dreams, dream recall",
    "Preparation":"Bitter tea or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable, \ud83e\udde0 Dream,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Silene capensis",
    "Category":"Oneirogen",
    "Effects":"Deep dreaming, ancestor contact",
    "Preparation":"Cold water root brew",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa",
    "Tags":"\u2615 Brewable, \ud83e\udde0 Dream,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Entada rheedii",
    "Category":"Oneirogen",
    "Effects":"Dream enhancement, trance",
    "Preparation":"Seed powder or chew",
    "Intensity":"Moderate",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83d\udc8a Oral, \ud83e\udde0 Dream,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Mugwort",
    "Category":"Oneirogen",
    "Effects":"Lucid dreams, astral travel",
    "Preparation":"Tea, smoke, or pillow herb",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable, \ud83e\udde0 Dream,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Heimia salicifolia (Sinicuichi)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Auditory hallucinations, slowed time",
    "Preparation":"Fermented sun tea",
    "Intensity":"Moderate",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83e\uddea Fermented,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Sceletium tortuosum (Kanna)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mood lift, empathy, sociability",
    "Preparation":"Chew, snuff, extract",
    "Intensity":"Moderate",
    "Onset":"30-60 min",
    "Legal Status":"Legal, sometimes restricted",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83d\udc8a Oral,\ud83d\udcab Euphoria,\u26a0\ufe0f Restricted",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Blue Lotus (Nymphaea caerulea)",
    "Category":"Other",
    "Effects":"Euphoria, aphrodisiac, dreamy calm",
    "Preparation":"Wine soak, smoke, tea",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Onset 30\u201360 min, oral or alcoholic extract. Mild duration (~2\u20133 hours).",
    "Therapeutic Uses":"Relaxation, aphrodisiac, mild euphoria, sleep aid.",
    "Side Effects":"Drowsiness, dizziness, dry mouth.",
    "Contraindications":"Avoid with MAOIs, sedatives, or alcohol.",
    "Drug Interactions":"May potentiate CNS depressants.",
    "Toxicity":"Low; very high doses can cause nausea and vomiting.",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Wild Dagga",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Cannabis-like buzz, mild euphoria",
    "Preparation":"Smoke or extract",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\ud83d\udcab Euphoria,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Damiana",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Aphrodisiac, relaxing, mood lifting",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal, banned in some countries",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udcab Euphoria,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Nelumbo nucifera (Sacred Lotus)",
    "Category":"Other",
    "Effects":"Spiritual clarity, calming euphoria",
    "Preparation":"Tea, tincture, smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83e\udde0 Cognitive,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Salvia divinorum",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Total dissociation, entity contact",
    "Preparation":"Smoked, intense, short duration",
    "Intensity":"High",
    "Onset":"1-5 min",
    "Legal Status":"Restricted in many regions",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\ud83c\udf00 Dissociation,\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Wild Lettuce",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Opium-like body high, sedation",
    "Preparation":"Smoke or extract",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Valerian Root",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Deep sedation, dream fog",
    "Preparation":"Tea or tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Kava Kava",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Body numbing, mind floating",
    "Preparation":"Brewed tea (not smoked)",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal, restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83c\udf00 Dissociation,\u26a0\ufe0f Restricted",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Acorus calamus",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Mild hallucinations, odd clarity",
    "Preparation":"Tea or chewed (effects debated)",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Banned for food use in US (asarone)",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83d\udc8a Oral,\ud83c\udf00 Dissociation,\ud83e\udde0 Cognitive,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Chiric Sanango",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Shadow work, spiritual clearing",
    "Preparation":"Amazonian brew; not casual use",
    "Intensity":"High",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Wormwood",
    "Category":"Ritual \/ Visionary",
    "Effects":"Bittersweet trance, visual haze",
    "Preparation":"Used in absinthe or smoked with caution",
    "Intensity":"Moderate",
    "Onset":"1-5 min",
    "Legal Status":"Legal, thujone regulated in some countries",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\ud83d\udd2e Ritual,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Mexican Tarragon",
    "Category":"Other",
    "Effects":"Visionary clarity, spiritual herb",
    "Preparation":"Tea, incense, or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udd6f\ufe0f Ritual,\ud83e\udde0 Cognitive,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Frankincense",
    "Category":"Ritual \/ Visionary",
    "Effects":"Meditative trance, sacred space",
    "Preparation":"Resin incense",
    "Intensity":"Mild",
    "Onset":"5-20 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd6f\ufe0f Ritual,\ud83d\udd2e Ritual,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Mapacho",
    "Category":"Ritual \/ Visionary",
    "Effects":"Sacred tobacco, heavy grounding",
    "Preparation":"Smoked ceremonially (very strong)",
    "Intensity":"High",
    "Onset":"1-5 min",
    "Legal Status":"Restricted (due to nicotine content)",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\ud83d\udd2e Ritual,\u26a0\ufe0f Restricted",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Datura \/ Brugmansia",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Full blackout, dreamlike confusion",
    "Preparation":"NOT safe \u2013 toxic, unpredictable",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Dangerous \/ Toxic \/ Controlled",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Nutmeg (high dose)",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Dissociation, nausea, hallucinations",
    "Preparation":"Dangerous doses needed; not recommended",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Discouraged \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Asparagus racemosus (Shatavari)",
    "Category":"Other",
    "Effects":"Spiritual dreaming, subtle energy shifts",
    "Preparation":"Tea or tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Tagetes lucida (Mexican Tarragon)",
    "Category":"Other",
    "Effects":"Visionary dreams, clarity",
    "Preparation":"Tea, incense, or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udd6f\ufe0f Ritual,\ud83e\udde0 Cognitive,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Turnera diffusa",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Same as Damiana \u2013 aphrodisiac, mood lift",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udcab Euphoria,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Kratom (Mitragyna speciosa)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Stimulant or sedative euphoria (dose-dependent)",
    "Preparation":"Oral only \u2013 not smoked",
    "Intensity":"High",
    "Onset":"1-5 min",
    "Legal Status":"Restricted in some regions",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\ud83d\udc8a Oral,\ud83d\udcab Euphoria,\u26a1 Stimulant,\u26a0\ufe0f Restricted",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Kra Thum Na \/ Kok",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Stimulation, kratom-like body feel",
    "Preparation":"Capsule or tea",
    "Intensity":"Moderate",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83d\udc8a Oral,\ud83d\udcab Euphoria,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Sakae Naa",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mild stimulant, mood separation",
    "Preparation":"Tea or capsule",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83d\udc8a Oral,\ud83d\udcab Euphoria,\u26a1 Stimulant,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Nelumbo nucifera",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mild dissociation, calm euphoria",
    "Preparation":"Tea, smoke",
    "Intensity":"Mild",
    "Onset":"1-5 min",
    "Legal Status":"Legal, low concern",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udcab Euphoria,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Scullcap (Scutellaria)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Relaxing, anxiety-reducing, dream support",
    "Preparation":"Tea or tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"California Poppy",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Gentle sedative, dreamlike calm",
    "Preparation":"Tea, tincture, or extract",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Hop Flowers",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Relaxation, dream enhancement",
    "Preparation":"Tea or herbal pillow",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Copal",
    "Category":"Ritual \/ Visionary",
    "Effects":"Purifying, sacred aroma, trance enhancement",
    "Preparation":"Burned as incense",
    "Intensity":"Mild",
    "Onset":"5-20 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd6f\ufe0f Ritual,\ud83d\udd2e Ritual,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Sweetgrass",
    "Category":"Ritual \/ Visionary",
    "Effects":"Positive energy, spiritual invocation",
    "Preparation":"Burned or braided for ceremonies",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd2e Ritual,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"White Sage",
    "Category":"Ritual \/ Visionary",
    "Effects":"Clarity, purification, spiritual reset",
    "Preparation":"Burned as incense",
    "Intensity":"Mild",
    "Onset":"5-20 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\ud83d\udd6f\ufe0f Ritual,\ud83d\udd2e Ritual,\ud83e\udde0 Cognitive,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Frankincense (Boswellia)",
    "Category":"Other",
    "Effects":"Trance, meditative awareness",
    "Preparation":"Resin burned",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf10 Global \/ Ritual",
    "Tags":"\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Henbane",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Delirium, hallucinations, anticholinergic",
    "Preparation":"Historically ritual; dangerous\/toxic",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Controlled \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83d\udd6f\ufe0f Ritual,\u2620\ufe0f Toxic",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Belladonna",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Hallucinations, dreamlike confusion",
    "Preparation":"Highly toxic \u2013 not for casual use",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Controlled \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Mandrake Root",
    "Category":"Deliriant \/ Toxic",
    "Effects":"Narcotic, visionary trance",
    "Preparation":"Traditional ceremonial use only",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Controlled \/ Toxic",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2620\ufe0f Toxic",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Anadenanthera peregrina (Yopo)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Powerful snuff, DMT-like visuals",
    "Preparation":"Prepared as snuff (contains bufotenine)",
    "Intensity":"High",
    "Onset":"1-3 min",
    "Legal Status":"Restricted in many regions",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Anadenanthera colubrina (Ceb\u00edl)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Entheogenic snuff, alternate reality feel",
    "Preparation":"South American use",
    "Intensity":"High",
    "Onset":"Varies",
    "Legal Status":"Restricted in many regions",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Virola spp.",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"DMT-containing tree resin",
    "Preparation":"Used in Amazonian snuffs",
    "Intensity":"High",
    "Onset":"1-3 min",
    "Legal Status":"Restricted \/ Controlled",
    "Region":"\ud83c\uddf2\ud83c\uddfd Latin America",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Acorus gramineus",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Cognitive clarity, trippy effects (debated)",
    "Preparation":"Tea or chewed",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udde8\ud83c\uddf3 East Asia",
    "Tags":"\u2615 Brewable,\ud83d\udc8a Oral,\ud83e\udde0 Cognitive,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Celastrus paniculatus (Intellect Tree)",
    "Category":"Other",
    "Effects":"Lucid dreaming, cognitive enhancer",
    "Preparation":"Oil or seeds consumed",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83e\udde0 Cognitive,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Silphium (extinct)",
    "Category":"Other",
    "Effects":"Ancient psychoactive\/contraceptive herb",
    "Preparation":"No longer available but worth note",
    "Intensity":"Mild",
    "Onset":"Varies",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Nymphaea ampla",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Sedative, euphoric, dreamlike states",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udcab Euphoria,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Pedicularis densiflora (Indian warrior)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Muscle relaxation, mild body high",
    "Preparation":"Smoked or tea",
    "Intensity":"Moderate",
    "Onset":"5-15 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa, \ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Pedicularis groenlandica",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Stronger relaxation, tension relief",
    "Preparation":"Smoked or tea",
    "Intensity":"Moderate",
    "Onset":"5-15 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0d Africa",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83c\udf00 Dissociation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Lactuca canadensis",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Wild lettuce relative, opium-like calm",
    "Preparation":"Tea or smoke",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83c\udf00 Dissociation,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Artemisia absinthium (Wormwood)",
    "Category":"Ritual \/ Visionary",
    "Effects":"Trance states, dream-like visuals",
    "Preparation":"Tea or smoke",
    "Intensity":"Moderate",
    "Onset":"15-45 min",
    "Legal Status":"Legal, thujone regulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udd2e Ritual,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Artemisia vulgaris (Mugwort)",
    "Category":"Oneirogen",
    "Effects":"Lucid dreaming, light hallucinations",
    "Preparation":"Smoke, tea, or ritual incense",
    "Intensity":"Mild",
    "Onset":"5-15 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udd6f\ufe0f Ritual, \ud83e\udde0 Dream,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Justicia pectoralis",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Aromatic, mild euphoria, anti-anxiety",
    "Preparation":"Smoked or brewed",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83d\udcab Euphoria,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Viola odorata (Sweet violet)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Mild sedative, calming, gentle dreaminess",
    "Preparation":"Tea or syrup",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Piper auritum (Root beer plant)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Calming, warming, euphoric",
    "Preparation":"Tea or culinary use",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83d\udcab Euphoria,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Eschscholzia californica (California poppy)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Sleep aid, mild dreamlike calm",
    "Preparation":"Tea, tincture",
    "Intensity":"Mild",
    "Onset":"15-45 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Rivea corymbosa",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Dreamy visuals, nausea, traditional Mazatec use",
    "Preparation":"Seeds ground and cold infused",
    "Intensity":"High",
    "Onset":"30-90 min",
    "Legal Status":"Restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Ipomoea tricolor (Heavenly Blue)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"LSD-like visuals, spiritual confusion",
    "Preparation":"Seeds ground and cold infused",
    "Intensity":"High",
    "Onset":"30-90 min",
    "Legal Status":"Restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Argyreia nervosa (Hawaiian Baby Woodrose)",
    "Category":"Ethnobotanical \/ Rare",
    "Effects":"Visionary, sedative, nausea-prone",
    "Preparation":"Cold water seed infusion",
    "Intensity":"High",
    "Onset":"30-90 min",
    "Legal Status":"Restricted in some countries",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\u26a0\ufe0f Restricted",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Tilia europaea (Linden flower)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Calming, relaxing, mild dream aid",
    "Preparation":"Tea",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddea\ud83c\uddfa Europe",
    "Tags":"\u2615 Brewable,\ud83c\udf00 Dissociation,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Melissa officinalis (Lemon balm)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Anxiolytic, cognitive calming",
    "Preparation":"Tea, tincture, or smoke",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83c\udf2c\ufe0f Smokable,\u2615 Brewable,\ud83c\udf00 Dissociation,\ud83e\udde0 Cognitive,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Ocimum sanctum (Holy Basil \/ Tulsi)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Mood lift, sacred calm, spiritual focus",
    "Preparation":"Tea or incense",
    "Intensity":"Mild",
    "Onset":"15-30 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable,\ud83d\udd6f\ufe0f Ritual,\ud83d\udcab Euphoria,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Rhodiola rosea",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Focus, reduced fatigue, mind clarity",
    "Preparation":"Capsule, tincture",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udf0e Unknown \/ Global",
    "Tags":"\ud83d\udc8a Oral,\ud83d\udcab Euphoria,\ud83e\udde0 Cognitive,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Withania somnifera (Ashwagandha)",
    "Category":"Dissociative \/ Sedative",
    "Effects":"Grounded calm, dream support",
    "Preparation":"Tea or capsule",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable,\ud83d\udc8a Oral,\ud83c\udf00 Dissociation,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":"Not Available"
  },
  {
    "Herb":"Bacopa monnieri",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Memory enhancer, mild calming",
    "Preparation":"Tea, capsule",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\uddee\ud83c\uddf3 India",
    "Tags":"\u2615 Brewable,\ud83d\udc8a Oral,\ud83d\udcab Euphoria,\ud83e\uddd8 Sedation,\u2705 Safe",
    "Mechanism of Action":"",
    "Pharmacokinetics":"",
    "Therapeutic Uses":"",
    "Side Effects":"",
    "Contraindications":"",
    "Drug Interactions":"",
    "Toxicity":"",
    "Toxicity \/ LD50":""
  },
  {
    "Herb":"Eleutherococcus senticosus (Siberian Ginseng)",
    "Category":"Empathogen \/ Euphoriant",
    "Effects":"Balanced energy, mood resilience",
    "Preparation":"Tea or extract",
    "Intensity":"Mild",
    "Onset":"30-60 min",
    "Legal Status":"Legal \/ Unregulated",
    "Region":"\ud83c\udde8\ud83c\uddf3 East Asia",
    "Tags":"\u2615 Brewable,\ud83d\udcab Euphoria,\u2705 Safe",
    "Mechanism of Action":"Not Available",
    "Pharmacokinetics":"Not Available",
    "Therapeutic Uses":"Not Available",
    "Side Effects":"Not Available",
    "Contraindications":"Not Available",
    "Drug Interactions":"Not Available",
    "Toxicity":"Not Available",
    "Toxicity \/ LD50":"Not Available"
  }
];